OnlineBookShop/Views/Shared/Components/Cart/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineBookShop.Helpers;
using OnlineBookShop.Db;

namespace OnlineBookShop.Views.Shared.Components.Cart
{
    public class CartViewComponent : ViewComponent
    {
        private readonly ICartsRepository _cartRepository;

        public CartViewComponent(ICartsRepository cartsRepository)
            {
                _cartRepository = cartsRepository;
            }

        public IViewComponentResult Invoke()
        {
            var cart = _cartRepository.TryGetByUserId(Constants.UserId);
            var cartViewModel = Mapping.ToCartViewModel(cart);
            var productcounts = cartViewModel?.Amount ?? 0;
            return View("Cart", productcounts);
        }


    }
}

OnlineBookShop/Views/Shared/Components/Favourites/FavouritesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineBookShop.Db;
using OnlineBookShop.Helpers;

namespace OnlineBookShop.Views.Shared.Components.Favourites
{
    public class FavouritesViewComponent : ViewComponent
    {
        private readonly IFavouritesRepository _favouritesRepository;

        public FavouritesViewComponent(IFavouritesRepository favouritesRepository)
            {
                _favouritesRepository = favouritesRepository;
            }

        public IViewComponentResult Invoke()
        {
            var favourites = _favouritesRepository.TryGetByUserId(Constants.UserId);
            var cartViewModel = Mapping.ToFavouritesViewModel(favourites);
            var favouritesCount = cartViewModel?.Amount ?? 0;
            return View("Favourites", favouritesCount);
        }
    }
}

OnlineBookShop/Views/Shared/Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - OnlineBookShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

OnlineBookShop/Views/Shared/Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 nav">
        <div class="container-fluid">
            <a class="nav-link btn-lg" asp-area="" asp-controller="home" asp-action="index">Название книжного магазина</a>
            <nav class="navbar bg-body-tertiary">
                <div class="container-fluid">
                    <form class="d-flex" role="search" method="post">
                        <input name="name" class="form-control" type="search" placeholder="Поиск" aria-label="Поиск">
                        <button class="btn btn-dark" type="submit" asp-controller="home" asp-action="search"> <i class="bi bi-search"></i> </button>
                    </form>
                </div>
            </nav>
            <nav class="nav justify-content-center">
                <a class="nav-link" asp-area="Administrator" asp-controller="Home" asp-action="Index"> <i class="bi bi-database"></i> Администратор </a>
                <a class="nav-link" asp-area="" asp-controller="authorization" asp-action="index">
                    <i class="bi bi-person"></i>
                        Войти
                </a>
                @await Component.InvokeAsync("Favourites")
                @await Component.InvokeAsync("Cart")
            </nav>
        </div>
    </nav>
</header>

OnlineBookShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineBookShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineBookShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
</head>
<body>
    @await Html.PartialAsync("Header")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("Footer")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>